name: Daily Conjecture Analysis

on:
  schedule:
    # Runs at 08:00 UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find Target Sequences
        run: python src/run_target_finder.py

      - name: Run Main Analyzer
        run: python src/main_analyzer.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Use a repo secret for the token
